export enum FilterTypeEnum {
  IsNull = '$isNull',
  IsNotNull = '$isNotNull',
  Contains = '$contains',
  NotContains = '$notContains',
  StartsWith = '$startsWith',
  EndsWith = '$endsWith',
  Is = '$is',
  Are = '$are',
  IsNot = '$isNot',
  GreaterThan = '$gt',
  GreaterThanEqual = '$gte',
  LessThan = '$lt',
  LessThanEqual = '$lte',
}
