export enum ResourceEnum {
  All = 'all',
  AnnualInfo = 'annual-info',
  Association = 'association',
  AssociationBeneficiaries = 'association-beneficiaries',
  Commodity = 'commodity',
  CommodityProduce = 'commodity-produce',
  Farm = 'farm',
  FarmProduce = 'farm-produce',
  Household = 'household',
  HouseholdBeneficiaries = 'household-beneficiaries',
  ProgramBeneficiaries = 'program-beneficiaries',
  Program = 'program',
  User = 'user',
}
